// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3j7Cxid6KbrEKHfdZvFTXmTjV0xGmw8',
    appId: '1:323935418840:web:09c489044ac816587f5aad',
    messagingSenderId: '323935418840',
    projectId: 'portfolio-x-carbon',
    authDomain: 'portfolio-x-carbon.firebaseapp.com',
    storageBucket: 'portfolio-x-carbon.firebasestorage.app',
    measurementId: 'G-YYJG3SN3J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLKCKeOB4fprNYuP8ItkeU2CpBG5F9sY',
    appId: '1:323935418840:android:469012330df0a54d7f5aad',
    messagingSenderId: '323935418840',
    projectId: 'portfolio-x-carbon',
    storageBucket: 'portfolio-x-carbon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZB9qxQuk_A7fvSw5P2YLO2GnAq-k_6c',
    appId: '1:323935418840:ios:6c97a320f6f51a317f5aad',
    messagingSenderId: '323935418840',
    projectId: 'portfolio-x-carbon',
    storageBucket: 'portfolio-x-carbon.firebasestorage.app',
    iosBundleId: 'com.example.portfolioCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhZB9qxQuk_A7fvSw5P2YLO2GnAq-k_6c',
    appId: '1:323935418840:ios:6c97a320f6f51a317f5aad',
    messagingSenderId: '323935418840',
    projectId: 'portfolio-x-carbon',
    storageBucket: 'portfolio-x-carbon.firebasestorage.app',
    iosBundleId: 'com.example.portfolioCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3j7Cxid6KbrEKHfdZvFTXmTjV0xGmw8',
    appId: '1:323935418840:web:d1134d1c24ec9fde7f5aad',
    messagingSenderId: '323935418840',
    projectId: 'portfolio-x-carbon',
    authDomain: 'portfolio-x-carbon.firebaseapp.com',
    storageBucket: 'portfolio-x-carbon.firebasestorage.app',
    measurementId: 'G-N0WMTRBD1L',
  );
}
